# These are supported funding model platforms
ko_fi: wurst
custom: https://www.wurstclient.net/donate/?utm_source=GitHub&utm_medium=ChestESP&utm_campaign=FUNDING.yml&utm_content=Sponsor+this+project
